### ISSUE TITLE
Can't include additional files to the bundle

### ISSUE THREAD

**Issue by vcarel** [elastic-coders/serverless-webpack#172]
I need to package ICU dat files with my bundle (I'm using lambda for an isomorphic app, so I need I18n support).

I tried to do so with:
```
# serverless.yml
package:
  include:
    - node_modules/full-icu/icudt59l.dat
```

... but nothing happens. The file is not included.
(mind that if I don't use the serverless-webpack plugin, it works fine)

Should it be supported? Is there another way to do so?

**Comment by HyperBrain** [comment]
Honestly I never ran into that problem, because I never had that requirement.
The plugin installs the node modules that are finally packaged separately, i.e. it packages exactly the modules that webpack requests after compiling the code.

That given, I think the only way to get it in is with a proper webpack configuration. Maybe there is a webpack plugin that can add arbitrary files or modules, that can be used in the webpack config.

**Comment by vcarel** [comment]
Thanks! Anyway, ICU are so troublesome that I'll try to make it without Intl at all.
BTW the ICU dat file is ~ 11MB zipped. I'm afraid of cold start times...

**Comment by vcarel** [comment]
So please close the issue :-)

**Comment by HyperBrain** [comment]
Will do :). And thanks for creating issues here 🙌  - a living community is really good for the project. And maybe someone stumbles over this and has a solution.
