### ISSUE TITLE
ES6 in webpack config

### ISSUE THREAD

**Issue by guillaumervls** [elastic-coders/serverless-webpack#192]
Hi and thanks for the module !

It seem that using ES6 in webpack's config file by naming it `webpack.config.babel.js` along with a `.babelrc` file ( http://www.romanfilippov.com/webpack-config-babel-js/ ) does not work with this plugin.

Am I missing something ?

Cheers

**Comment by HyperBrain** [comment]
Hi @guillaumervls , thanks for the question 👍 

The whole Serverless framework does not use ES6 nor babel to run as it is part of the infrastructure and not part of the deployed product.

You would need to have babel-register initialized within the Serverless framework startup, which is not planned as far as I know (the framework would have to initialize it prior of loading the config).

This would add unnecessary technical debt and make debugging of Serverless and the plugin more complex, as babel-register hooks "require" to to an on-the-fly babel transpilation (including source maps, etc.).

Of course one can write a small plugin that initializes babel-register in its startup and enables it for the whole toolchain, but I do not see that as part of the framework itself and out of scope for the toolchain as it might have side-effects on all other plugins and the framework itself (because of the global require hook).

**Comment by guillaumervls** [comment]
Thanks @HyperBrain for this quick and precise answer !

I don't know how the framework and the plugin work internally. I (naively ?) thought that this plugin spawned a separate child process executing webpack.

**Comment by HyperBrain** [comment]
It uses the webpack API under the hood, and is completely executed within the context/process of the Serverless framework. All Serverless plugins work this way ;-) For the webpack part, it is more integrative to do it the API way if you're integrating it. Out-of-process execution of tools most often have some drawbacks (but if there's no API available you have no other chance) 😄

**Comment by guillaumervls** [comment]
Thanks for the explanation ! I guess we can close this.
