### ISSUE TITLE
Make webpack aware of stage/region

### ISSUE THREAD

**Issue by Spaider** [elastic-coders/serverless-webpack#86]
I need a fresh look at my problem. I am using serverless 1.x and want to deploy to different regions with different stages (surprise, huh? :) ) Every stage/region has its own set of settings, DB connection options, to be precise. 

Everything was more or less good before I decided to introduce webpack plugin: region/stage-specific options were stored in ${region}.${stage}.env files and I load them with dot-env. 

It's not possible anymore when I started to use `webpack` plugin. Well, at least solution is avoiding me. The only way to achieve similar functionality is to define all the variables in `serverless.yml` file and resolve them indirectly via `${opt:stage}` and `${opt:region}` variables. I do not like this for two reasons: 

- all credentials are defined in one file and has to be committed to repo
- very verbose syntax, which essentially repeats itself for every stage/region compilation

I am thinking, if stage/region information will be available during webpack'ing phase then it will be possible to dynamically load necessary settings with help of `dotenv-webpack` plugin.

May be I am missing something or even trying to approach the problem from the wrong site.

Any ideas will be much appreciated.

Thanks.

**Comment by hassankhan** [comment]
I've posted my workaround for this issue [here](https://github.com/dherault/serverless-offline/issues/189).

**Comment by HyperBrain** [comment]
There have been vast improvements made in Serverless in the last few versions, especially for the variable system. E.g. it is now possible to have variables stored externally (S3) because the variable system has been been switched to asynchronous retrieval. Even CF output variables can be referenced and imported into variables now.

With this in mind, does the issue mentioned here still persist?

**Comment by hassankhan** [comment]
It still does unfortunately, although I'm not sure whether `serverless-webpack` or `serverless-offline` should be handling inserting env vars.

**Comment by HyperBrain** [comment]
We even use [`serverless-export-env`](https://github.com/arabold/serverless-export-env) in combination with webpack/offline. This makes sure that for local runs the environment is set correctly.

**Comment by hassankhan** [comment]
@HyperBrain How do you load the `.env` into your handlers? Via a bootstrap script or using something like `webpack-dotenv`?

**Comment by HyperBrain** [comment]
The export-env plugin sets the environment variables defined for your lambdas correctly when you use serverless-offline. That's the only way we use to get them set. Maybe @arabold can provide some details for his plugin.

**Comment by arabold** [comment]
@Spaider I fail to see how an external `.env` file that's loaded with dotenv relates to the `serverless-webpack` plugin. I _assume_ that what happens is that webpack bundles the `.env` file directly in the package depending on which stage is being built. So if you build stage "dev" for "us-east-1" it automatically bundles the `us-east-1.dev.env" file and thus prevents you to use the same build package for other regions and stages? If that's the case then this can typically be solved via either the `webpack.config`.

The `serverless-export-env` plugin doesn't really solve much here IMO. It's purpose is to expose environment variables defined in the `serverless.yml` and referencing CloudFormation resources to your _local_ environment, e.g. during running local tests (think `npm test`) or when using the `serverless-offline` plugin. But that's not the problem here.

**Comment by Spaider** [comment]
Sorry guys, it was so long ago, I had been drawn to other projects already. Not sure if I will have time to check this soon.

**Comment by HyperBrain** [comment]
@Spaider No problem. It was serverless-webpack that fell asleep like Sleeping Beauty for quite a long time 😃 so it's not your fault. But we kissed it alive again.
I will close the issue then. Feel free to reopen it if you have time to check it in the future.
